### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by BrunoGM** [blmarquess/hackintosh-i9-11900H#1]
Acredito que seja impossível fazer o sleep funcionar nesse hackintosh, nem no windows ele funciona.

**Comment by blmarquess** [comment]
Então, como não utilizo windows nunca testei la para ver se ele estava ok.

Aqui esta tudo bem configurado e se eu colocar para suspender ele até inicia a suspensão mas não conclui e volta para tela de login.

No meu caso não me incomoda na maior parte do tempo o que mudou na minha rotina usando ele para trabalhar foi desligar quando parar de trabalhar que usando a maquina anterior eu desligava so para fazer manutenção preventiva.

mas vou marcar ali como não funcional ja que vc me deu essa informação que até no windows ele não funciona certo.
